# Generated by Django 3.0.1 on 2019-12-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativewriting', '0003_auto_20191227_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
