# Generated by Django 3.0.1 on 2019-12-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativewriting', '0004_remove_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=12),
        ),
    ]
