# Generated by Django 3.0.1 on 2020-01-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativewriting', '0005_auto_20191231_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
