# Generated by Django 3.0.1 on 2020-01-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativewriting', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
